### ISSUE TITLE
Moving to soft tabs?

### ISSUE THREAD

**Issue by cclauss** [coomlata1/pythonista-scripts#11]
This is OPTIONAL but please consider doing this: http://omz-forums.appspot.com/pythonista/post/5316756860043264

You might want 2 spaces per tab instead of 4 for iPhone screen.

Moving to spaces instead of tabs make it easier to edit code directly in the GitHub webpages.

**Comment by coomlata1** [comment]
Hi...
Did as you instructed on the soft tabs business.  I hope this will help the transition between phone and GitHub.  Right now I have to do a lot of stripping of unwanted characters at the front of the code line when I get scripts off of GitHub and copy them to my phone. I know it's been talked about in the forum, but sometimes Pythonista crashes when I am doing this. Since I started using the carriage return zapper I haven't experienced a crash.

I REALLY like your changes.  The code is now very tight and easy to understand.  I particularly like the way you shored up those try-exception lines and cleaned up the text formatting routines.  I learned and am learning a lot from your coding abilities.  I really appreciate your willingness to jump in and help with this...not a lot of people would bother.  I plan on continuing my python work and I will consider you to be my first source for questions and advice.  Also...I promise I will spell your name right in the future!!!!
